version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - bridge

  app:
    image: app:latest
    container_name: "app"
    restart: always
    build:
      context: .
    networks:
      - bridge
    ports:
      - "34001:8080"
    depends_on:
      mysql:
        condition: service_healthy

networks:
  bridge:
